language: node_js
sudo: required
node_js: 
  - 8.12.0

cache:
  directories:
    - node_modules

branches:
  only:
    - master 

before_install:
  - npm install -g hexo

# S: Build Lifecycle
install:
  - npm install
  # - npm install hexo-deployer-git --save

# before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "a2dict"
  - git config user.email "a2dict@163.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

after_success:
  - cd public && find . -type f -exec curl -u ${FTP_USER}:${FTP_PASSWD} --ftp-create-dirs -T {} ftp://a2dict.ftp-gz01.bcehost.com/webroot/{} \;